# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cbf7a8c941604677d8505894986bcccb363fb25d4c36a58317c361c5bdda8126b67c6f59a8a92c5edd20cf127a9cca2e55cd40846dad2a5aa7b0da7f8e43955f

test:
  secret_key_base: f8a6de59976d44d2d020bcb6305133e3d308488dcf740bbfad98f95901dc39ee0ef4ffbc6b85fbf9f0e3c92fdbfddb710820851cbf5f315034080f37c80bcac2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
